# Generated by Django 5.2.4 on 2025-12-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianinstrument',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='core.musician'),
        ),
    ]
