# Generated by Django 5.2.4 on 2025-12-12 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_instrument_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="piece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editions",
                to="core.piece",
            ),
        ),
    ]
