# Generated by Django 5.2.4 on 2026-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_seed_core_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="partasset",
            name="asset_type",
            field=models.CharField(
                choices=[("Clean", "Clean"), ("Bowing", "Bowing")],
                default="Clean",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Pieces", "Pieces"),
                    ("Roster", "Roster"),
                    ("Assignment", "Assignment"),
                    ("Delivered", "Delivered"),
                ],
                default="Created",
                max_length=255,
            ),
        ),
    ]
