# Generated by Django 5.2.4 on 2026-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_partasset_asset_type_alter_program_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="programmusician",
            constraint=models.UniqueConstraint(
                fields=("program", "musician"), name="unique_program_musician"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmusicianinstrument",
            constraint=models.UniqueConstraint(
                fields=("program_musician", "instrument"),
                name="unique_program_musician_instrument",
            ),
        ),
    ]
