# Generated by Django 5.2.4 on 2026-02-15 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_programmusician_unique_program_musician_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="overrides_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProgramChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pieces_completed_on", models.DateTimeField(blank=True, null=True)),
                ("roster_completed_on", models.DateTimeField(blank=True, null=True)),
                ("overrides_completed_on", models.DateTimeField(blank=True, null=True)),
                ("bowings_completed_on", models.DateTimeField(blank=True, null=True)),
                ("assignments_sent_on", models.DateTimeField(blank=True, null=True)),
                (
                    "assignments_completed_on",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("delivery_sent_on", models.DateTimeField(blank=True, null=True)),
                ("delivery_completed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "assignments_completed_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignments_sent_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bowings_completed_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_sent_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "overrides_completed_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pieces_completed_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="core.program",
                    ),
                ),
                (
                    "roster_completed_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
