# Generated by Django 5.2.4 on 2026-02-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_program_overrides_enabled_programchecklist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="overrides_enabled",
        ),
    ]
