# Generated by Django 5.2.4 on 2026-02-16 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_program_overrides_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="status",
        ),
    ]
