# Generated by Django 5.2.4 on 2026-02-16 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_program_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[("Email", "Email")], default="Email", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Assignment", "Assignment")], max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Sent", "Sent"),
                            ("Failed", "Failed"),
                        ],
                        default="Created",
                        max_length=255,
                    ),
                ),
                ("recipient_email", models.CharField(max_length=255)),
                ("recipient_first_name", models.CharField(max_length=255)),
                ("recipient_last_name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("body_html", models.TextField()),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.program",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.musician",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
