# Generated by Django 5.2.4 on 2026-02-17

import django.db.models.deletion
import uuid
from django.db import migrations, models
import core.models.notifications


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="programpartmusician",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.program",
            ),
        ),
        migrations.AddConstraint(
            model_name="programpartmusician",
            constraint=models.UniqueConstraint(
                fields=("program", "part"), name="unique_program_part_assignment"
            ),
        ),
        migrations.CreateModel(
            name="MagicLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=core.models.notifications.generate_magic_link_token,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Assignment", "Assignment")],
                        default="Assignment",
                        max_length=255,
                    ),
                ),
                ("expires_on", models.DateTimeField()),
                ("last_accessed_on", models.DateTimeField(blank=True, null=True)),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.program",
                    ),
                ),
                (
                    "musician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.musician",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="magic_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.magiclink",
            ),
        ),
    ]
