# Generated by Django 5.2.4 on 2026-02-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_magic_links_and_program_part_assignments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Assignment", "Assignment"),
                    ("Part Delivery", "Part Delivery"),
                ],
                max_length=255,
            ),
        ),
    ]
