# Generated by Django 5.2.4 on 2026-02-17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclink",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="magiclink",
            name="revoked",
            field=models.BooleanField(default=False),
        ),
    ]
